#pragma once
#include <string>
//texture id
enum CFG_TEXTURE_ID 
{
	CFG_TEXTURE_ID_STONE,
	CFG_TEXTURE_ID_GRANITE,
	CFG_TEXTURE_ID_POLISHED_GRANITE,
	CFG_TEXTURE_ID_DIORITE,
	CFG_TEXTURE_ID_POLISHED_DIORITE,
	CFG_TEXTURE_ID_ANDESITE,
	CFG_TEXTURE_ID_POLISHED_ANDESITE,
	CFG_TEXTURE_ID_GRASS_BLOCK,
	CFG_TEXTURE_ID_GRASS_BLOCK_TOP,
	CFG_TEXTURE_ID_DIRT,
	CFG_TEXTURE_ID_COBBLESTONE,
	CFG_TEXTURE_ID_OAK_PLANKS,
	CFG_TEXTURE_ID_SPRUCE_PLANKS,
	CFG_TEXTURE_ID_BRICH_PLANKS,
	CFG_TEXTURE_ID_JUNGLE_PLANKS,
	CFG_TEXTURE_ID_ACACIA_PLANKS,
	CFG_TEXTURE_ID_DARK_OAK_PLANKS,
	CFG_TEXTURE_ID_BEDROCK,
	CFG_TEXTURE_ID_SAND,

	CFG_TEXTURE_ID_LAST
};

#define CFG_TEXTURE_DIRECTORY "data\\textures\\blocks\\"

//texture id to texture file name
#define CFG_TEXTURE_GET_FILE_NAME(CFG_TEXTURE_ID_STONE) CFG_TEXTURE_DIRECTORY + "stone.png"
#define CFG_TEXTURE_GET_FILE_NAME(CFG_TEXTURE_ID_GRANITE) CFG_TEXTURE_DIRECTORY + "stone_granite.png"
#define CFG_TEXTURE_GET_FILE_NAME(CFG_TEXTURE_ID_POLISHED_GRANITE) CFG_TEXTURE_DIRECTORY + "stone_granite_smooth.png"
#define CFG_TEXTURE_GET_FILE_NAME(CFG_TEXTURE_ID_DIORITE) CFG_TEXTURE_DIRECTORY + "stone_diorite.png"
#define CFG_TEXTURE_GET_FILE_NAME(CFG_TEXTURE_ID_POLISHED_DIORITE) CFG_TEXTURE_DIRECTORY + "stone_diorite_smooth.png"
#define CFG_TEXTURE_GET_FILE_NAME(CFG_TEXTURE_ID_ANDESITE) CFG_TEXTURE_DIRECTORY + "stone_andesite.png"
#define CFG_TEXTURE_GET_FILE_NAME(CFG_TEXTURE_ID_POLISHED_ANDESITE) CFG_TEXTURE_DIRECTORY + "stone_andesite_smooth.png"
#define CFG_TEXTURE_GET_FILE_NAME(CFG_TEXTURE_ID_GRASS_BLOCK) CFG_TEXTURE_DIRECTORY + "grass_side.png"
#define CFG_TEXTURE_GET_FILE_NAME(CFG_TEXTURE_ID_GRASS_BLOCK_TOP) CFG_TEXTURE_DIRECTORY + "grass_top.png"
#define CFG_TEXTURE_GET_FILE_NAME(CFG_TEXTURE_ID_DIRT) CFG_TEXTURE_DIRECTORY + "dirt.png"
#define CFG_TEXTURE_GET_FILE_NAME(CFG_TEXTURE_ID_COBBLESTONE) CFG_TEXTURE_DIRECTORY + "cobblestone.png"
#define CFG_TEXTURE_GET_FILE_NAME(CFG_TEXTURE_ID_OAK_PLANKS) CFG_TEXTURE_DIRECTORY + "planks_oak.png"
#define CFG_TEXTURE_GET_FILE_NAME(CFG_TEXTURE_ID_SPRUCE_PLANKS) CFG_TEXTURE_DIRECTORY + "planks_spruce.png"
#define CFG_TEXTURE_GET_FILE_NAME(CFG_TEXTURE_ID_BRICH_PLANKS) CFG_TEXTURE_DIRECTORY + "planks_birch.png"
#define CFG_TEXTURE_GET_FILE_NAME(CFG_TEXTURE_ID_JUNGLE_PLANKS) CFG_TEXTURE_DIRECTORY + "planks_jungle.png"
#define CFG_TEXTURE_GET_FILE_NAME(CFG_TEXTURE_ID_ACACIA_PLANKS) CFG_TEXTURE_DIRECTORY + "planks_acacia.png"
#define CFG_TEXTURE_GET_FILE_NAME(CFG_TEXTURE_ID_DARK_OAK_PLANKS) CFG_TEXTURE_DIRECTORY + "planks_big_oak.png"
#define CFG_TEXTURE_GET_FILE_NAME(CFG_TEXTURE_ID_BEDROCK) CFG_TEXTURE_DIRECTORY + "bedrock.png"
#define CFG_TEXTURE_GET_FILE_NAME(CFG_TEXTURE_ID_SAND) CFG_TEXTURE_DIRECTORY + "sand.png"

namespace game
{
	namespace config 
	{




	
	}
}